#!/bin/sh

set -e

case "$1" in
    configure)
	if [ -e /usr/lib/syslinux/vesamenu.c32 ]; then
        	ln -s /usr/lib/syslinux/vesamenu.c32 /usr/share/syslinux/themes/minimal/extlinux/vesamenu.c32
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
